apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: daprio-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/lburgazzoli/dapr-operator-ng-catalog:latest
  displayName: dapr.io catalog
  grpcPodConfig:
    securityContextConfig: restricted
  publisher: dapr.io
  updateStrategy:
    registryPoll:
      interval: 10m
