/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/lburgazzoli/dapr-operator-ng/api/dapr/v1alpha1"
	daprv1alpha1 "github.com/lburgazzoli/dapr-operator-ng/pkg/client/dapr/applyconfiguration/dapr/v1alpha1"
	scheme "github.com/lburgazzoli/dapr-operator-ng/pkg/client/dapr/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DaprsGetter has a method to return a DaprInterface.
// A group's client should implement this interface.
type DaprsGetter interface {
	Daprs(namespace string) DaprInterface
}

// DaprInterface has methods to work with Dapr resources.
type DaprInterface interface {
	Create(ctx context.Context, dapr *v1alpha1.Dapr, opts v1.CreateOptions) (*v1alpha1.Dapr, error)
	Update(ctx context.Context, dapr *v1alpha1.Dapr, opts v1.UpdateOptions) (*v1alpha1.Dapr, error)
	UpdateStatus(ctx context.Context, dapr *v1alpha1.Dapr, opts v1.UpdateOptions) (*v1alpha1.Dapr, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Dapr, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.DaprList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Dapr, err error)
	Apply(ctx context.Context, dapr *daprv1alpha1.DaprApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Dapr, err error)
	ApplyStatus(ctx context.Context, dapr *daprv1alpha1.DaprApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Dapr, err error)
	DaprExpansion
}

// daprs implements DaprInterface
type daprs struct {
	client rest.Interface
	ns     string
}

// newDaprs returns a Daprs
func newDaprs(c *DaprV1alpha1Client, namespace string) *daprs {
	return &daprs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the dapr, and returns the corresponding dapr object, and an error if there is any.
func (c *daprs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Dapr, err error) {
	result = &v1alpha1.Dapr{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("daprs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Daprs that match those selectors.
func (c *daprs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DaprList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DaprList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("daprs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested daprs.
func (c *daprs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("daprs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a dapr and creates it.  Returns the server's representation of the dapr, and an error, if there is any.
func (c *daprs) Create(ctx context.Context, dapr *v1alpha1.Dapr, opts v1.CreateOptions) (result *v1alpha1.Dapr, err error) {
	result = &v1alpha1.Dapr{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("daprs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dapr).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a dapr and updates it. Returns the server's representation of the dapr, and an error, if there is any.
func (c *daprs) Update(ctx context.Context, dapr *v1alpha1.Dapr, opts v1.UpdateOptions) (result *v1alpha1.Dapr, err error) {
	result = &v1alpha1.Dapr{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("daprs").
		Name(dapr.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dapr).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *daprs) UpdateStatus(ctx context.Context, dapr *v1alpha1.Dapr, opts v1.UpdateOptions) (result *v1alpha1.Dapr, err error) {
	result = &v1alpha1.Dapr{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("daprs").
		Name(dapr.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dapr).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the dapr and deletes it. Returns an error if one occurs.
func (c *daprs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("daprs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *daprs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("daprs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched dapr.
func (c *daprs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Dapr, err error) {
	result = &v1alpha1.Dapr{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("daprs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied dapr.
func (c *daprs) Apply(ctx context.Context, dapr *daprv1alpha1.DaprApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Dapr, err error) {
	if dapr == nil {
		return nil, fmt.Errorf("dapr provided to Run must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(dapr)
	if err != nil {
		return nil, err
	}
	name := dapr.Name
	if name == nil {
		return nil, fmt.Errorf("dapr.Name must be provided to Run")
	}
	result = &v1alpha1.Dapr{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("daprs").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *daprs) ApplyStatus(ctx context.Context, dapr *daprv1alpha1.DaprApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Dapr, err error) {
	if dapr == nil {
		return nil, fmt.Errorf("dapr provided to Run must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(dapr)
	if err != nil {
		return nil, err
	}

	name := dapr.Name
	if name == nil {
		return nil, fmt.Errorf("dapr.Name must be provided to Run")
	}

	result = &v1alpha1.Dapr{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("daprs").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
