/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "github.com/lburgazzoli/dapr-operator-ng/api/dapr/v1alpha1"
	daprv1alpha1 "github.com/lburgazzoli/dapr-operator-ng/pkg/client/dapr/applyconfiguration/dapr/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDaprs implements DaprInterface
type FakeDaprs struct {
	Fake *FakeDaprV1alpha1
	ns   string
}

var daprsResource = v1alpha1.SchemeGroupVersion.WithResource("daprs")

var daprsKind = v1alpha1.SchemeGroupVersion.WithKind("Dapr")

// Get takes name of the dapr, and returns the corresponding dapr object, and an error if there is any.
func (c *FakeDaprs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Dapr, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(daprsResource, c.ns, name), &v1alpha1.Dapr{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Dapr), err
}

// List takes label and field selectors, and returns the list of Daprs that match those selectors.
func (c *FakeDaprs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DaprList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(daprsResource, daprsKind, c.ns, opts), &v1alpha1.DaprList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DaprList{ListMeta: obj.(*v1alpha1.DaprList).ListMeta}
	for _, item := range obj.(*v1alpha1.DaprList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested daprs.
func (c *FakeDaprs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(daprsResource, c.ns, opts))

}

// Create takes the representation of a dapr and creates it.  Returns the server's representation of the dapr, and an error, if there is any.
func (c *FakeDaprs) Create(ctx context.Context, dapr *v1alpha1.Dapr, opts v1.CreateOptions) (result *v1alpha1.Dapr, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(daprsResource, c.ns, dapr), &v1alpha1.Dapr{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Dapr), err
}

// Update takes the representation of a dapr and updates it. Returns the server's representation of the dapr, and an error, if there is any.
func (c *FakeDaprs) Update(ctx context.Context, dapr *v1alpha1.Dapr, opts v1.UpdateOptions) (result *v1alpha1.Dapr, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(daprsResource, c.ns, dapr), &v1alpha1.Dapr{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Dapr), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDaprs) UpdateStatus(ctx context.Context, dapr *v1alpha1.Dapr, opts v1.UpdateOptions) (*v1alpha1.Dapr, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(daprsResource, "status", c.ns, dapr), &v1alpha1.Dapr{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Dapr), err
}

// Delete takes name of the dapr and deletes it. Returns an error if one occurs.
func (c *FakeDaprs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(daprsResource, c.ns, name, opts), &v1alpha1.Dapr{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDaprs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(daprsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DaprList{})
	return err
}

// Patch applies the patch and returns the patched dapr.
func (c *FakeDaprs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Dapr, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(daprsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Dapr{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Dapr), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied dapr.
func (c *FakeDaprs) Apply(ctx context.Context, dapr *daprv1alpha1.DaprApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Dapr, err error) {
	if dapr == nil {
		return nil, fmt.Errorf("dapr provided to Apply must not be nil")
	}
	data, err := json.Marshal(dapr)
	if err != nil {
		return nil, err
	}
	name := dapr.Name
	if name == nil {
		return nil, fmt.Errorf("dapr.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(daprsResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.Dapr{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Dapr), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeDaprs) ApplyStatus(ctx context.Context, dapr *daprv1alpha1.DaprApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Dapr, err error) {
	if dapr == nil {
		return nil, fmt.Errorf("dapr provided to Apply must not be nil")
	}
	data, err := json.Marshal(dapr)
	if err != nil {
		return nil, err
	}
	name := dapr.Name
	if name == nil {
		return nil, fmt.Errorf("dapr.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(daprsResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.Dapr{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Dapr), err
}
