apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: dapr-control-plane--leader-election-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: dapr-control-plane
    app.kubernetes.io/managed-by: kustomize
  name: dapr-control-plane-leader-election-rolebinding
  namespace: dapr-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dapr-control-plane-leader-election-role
subjects:
- kind: ServiceAccount
  name: dapr-control-plane-sa
  namespace: dapr-system
