apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: dapr-controller-leader-election-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dapr-operator-ng
    app.kubernetes.io/part-of: dapr-operator-ng
    app.kubernetes.io/managed-by: kustomize
  name: dapr-controller-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dapr-controller-leader-election-role
subjects:
- kind: ServiceAccount
  name: dapr-controller-sa
  namespace: dapr-system
