---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dapr-operator
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - dapr.dapr.io
  resources:
  - daprs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dapr.dapr.io
  resources:
  - daprs/finalizers
  verbs:
  - update
- apiGroups:
  - dapr.dapr.io
  resources:
  - daprs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dapr.io
  resources:
  - components
  verbs:
  - '*'
- apiGroups:
  - dapr.io
  resources:
  - components/finalizers
  verbs:
  - '*'
- apiGroups:
  - dapr.io
  resources:
  - components/status
  verbs:
  - '*'
- apiGroups:
  - dapr.io
  resources:
  - configurations
  verbs:
  - '*'
- apiGroups:
  - dapr.io
  resources:
  - configurations/finalizers
  verbs:
  - '*'
- apiGroups:
  - dapr.io
  resources:
  - configurations/status
  verbs:
  - '*'
- apiGroups:
  - dapr.io
  resources:
  - resiliencies
  verbs:
  - '*'
- apiGroups:
  - dapr.io
  resources:
  - resiliencies/finalizers
  verbs:
  - '*'
- apiGroups:
  - dapr.io
  resources:
  - resiliencies/status
  verbs:
  - '*'
- apiGroups:
  - dapr.io
  resources:
  - subscriptions
  verbs:
  - '*'
- apiGroups:
  - dapr.io
  resources:
  - subscriptions/finalizers
  verbs:
  - '*'
- apiGroups:
  - dapr.io
  resources:
  - subscriptions/status
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - '*'
