apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: dapr-control-plane-clusterrolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: dapr-control-plane
    app.kubernetes.io/managed-by: kustomize
  name: dapr-control-plane-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dapr-control-plane-role
subjects:
- kind: ServiceAccount
  name: dapr-control-plane-sa
  namespace: dapr-system
