apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: dapr-control-plane-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: dapr-control-plane
    app.kubernetes.io/managed-by: kustomize
  name: dapr-control-plane-sa
  namespace: dapr-system
