/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	toolsv1alpha1 "github.com/lburgazzoli/dapr-operator-ng/api/tools/v1alpha1"
	versioned "github.com/lburgazzoli/dapr-operator-ng/pkg/client/tools/clientset/versioned"
	internalinterfaces "github.com/lburgazzoli/dapr-operator-ng/pkg/client/tools/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/lburgazzoli/dapr-operator-ng/pkg/client/tools/listers/tools/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DaprInformer provides access to a shared informer and lister for
// Daprs.
type DaprInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DaprLister
}

type daprInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDaprInformer constructs a new informer for Dapr type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDaprInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDaprInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDaprInformer constructs a new informer for Dapr type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDaprInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ToolsV1alpha1().Daprs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ToolsV1alpha1().Daprs(namespace).Watch(context.TODO(), options)
			},
		},
		&toolsv1alpha1.Dapr{},
		resyncPeriod,
		indexers,
	)
}

func (f *daprInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDaprInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *daprInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&toolsv1alpha1.Dapr{}, f.defaultInformer)
}

func (f *daprInformer) Lister() v1alpha1.DaprLister {
	return v1alpha1.NewDaprLister(f.Informer().GetIndexer())
}
