name: "e2e - bundle"

on:
  workflow_call:

jobs:
  images:
    runs-on: ubuntu-latest
    outputs:
      operatorImage: ${{ steps.publish.outputs.operatorImage }}
      bundleImage: ${{ steps.publish.outputs.bundleImage }}
      catalogImage: ${{ steps.publish.outputs.catalogImage }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Set up Go"
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: "Publish Images"
        id: "publish"
        run: |
          export UUID=$(uuidgen | tr "[:upper:]" "[:lower:]")
          
          export CONTAINER_IMAGE="ttl.sh/${UUID}-${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}:1h"
          export BUNDLE_CONTAINER_IMAGE="ttl.sh/${UUID}-${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}-bundle:1h"
          export CATALOG_CONTAINER_IMAGE="ttl.sh/${UUID}-${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}-catalog:1h"
          
          echo CONTAINER_IMAGE
          echo BUNDLE_CONTAINER_IMAGE
          echo CATALOG_CONTAINER_IMAGE
          
          echo "operatorImage=${CONTAINER_IMAGE}" >> "$GITHUB_OUTPUT"
          echo "bundleImage=${BUNDLE_CONTAINER_IMAGE}" >> "$GITHUB_OUTPUT"
          echo "catalogImage=${CATALOG_CONTAINER_IMAGE}" >> "$GITHUB_OUTPUT"
          
          make docker/build 
          make docker/push
          
          make bundle/generate
          make bundle/build
          make bundle/push
                    
          make catalog/build
          make catalog/push
  e2e-bundle:
    runs-on: ubuntu-latest
    needs:
      - images
    env:
      CONTAINER_IMAGE: ${{needs.images.outputs.operatorImage}}
      BUNDLE_CONTAINER_IMAGE: ${{needs.images.outputs.bundleImage}}
      CATALOG_CONTAINER_IMAGE: ${{needs.images.outputs.catalogImage}}
    strategy:
      matrix:
        kubernetes-version:
          - "1.27.3"
          - "1.28.0"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "SetUp Go"
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: 'SetUp KinD'
        uses: container-tools/kind-action@v2
        with:
          version: "v0.20.0"
          kubectl_version: v${{ matrix.kubernetes-version }}
          registry: false
          node_image: kindest/node:v${{ matrix.kubernetes-version }}
          config: test/e2e/kind.yaml
      - name: "SetUp OLM"
        run: |          
          make olm/install
          
          kubectl wait \
            --namespace=olm \
            --for=condition=ready \
            pod \
            --selector=app=olm-operator \
            --timeout=90s
          
          kubectl wait \
            --namespace=olm \
            --for=condition=ready \
            pod \
            --selector=app=catalog-operator \
            --timeout=90s
