name: Build And Push

on:
  workflow_call:

jobs:
  images:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.publish.outputs.image }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Set up Go"
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: "Publish Image"
        id: "publish"
        run: |
          export UUID=$(uuidgen | tr "[:upper:]" "[:lower:]")
          export CONTAINER_IMAGE="ttl.sh/${UUID}-${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}:1h"
          
          echo CONTAINER_IMAGE
          echo "image=${CONTAINER_IMAGE}" >> "$GITHUB_OUTPUT"
          
          make docker/build docker/push
  e2e:
    runs-on: ubuntu-latest
    needs:
      - images
    env:
      CONTAINER_IMAGE: ${{needs.images.outputs.image}}
    strategy:
      matrix:
        kubernetes-version:
          - "1.27.3"
          - "1.28.0"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "SetUp Go"
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: 'SetUp KinD'
        uses: container-tools/kind-action@v2
        with:
          version: "v0.20.0"
          kubectl_version: v${{ matrix.kubernetes-version }}
          registry: false
          node_image: kindest/node:v${{ matrix.kubernetes-version }}
          config: test/e2e/kind.yaml
#      - name: 'SetUp Kind Ingress'
#        run: |
#          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
#
#          kubectl wait \
#            --namespace=ingress-nginx \
#            --for=condition=ready \
#            pod \
#            --selector=app.kubernetes.io/component=controller \
#            --timeout=90s
#      - name: 'SetUp Cert Manager'
#        run: |
#          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.12.0/cert-manager.yaml
#
#          kubectl wait \
#            --namespace=cert-manager \
#            --for=condition=ready \
#            pod \
#            --selector=app.kubernetes.io/instance=cert-manager,app.kubernetes.io/name=cert-manager \
#            --timeout=90s
#
#          kubectl wait \
#            --namespace=cert-manager \
#            --for=condition=ready \
#            pod \
#            --selector=app.kubernetes.io/instance=cert-manager,app.kubernetes.io/name=cainjector \
#            --timeout=90s
#
#          kubectl wait \
#            --namespace=cert-manager \
#            --for=condition=ready \
#            pod \
#            --selector=app.kubernetes.io/instance=cert-manager,app.kubernetes.io/name=webhook \
#            --timeout=90s
      - name: "SetUp Dapr Operator"
        run: |          
          make deploy/e2e
          
          kubectl wait \
            --namespace=dapr-system \
            --for=condition=ready \
            pod \
            --selector=control-plane=dapr-control-plane \
            --timeout=90s
      - name: "Run e2e"
        run: |
          make test/e2e
