
name: Push

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      olm:
        required: true
        type: boolean
    secrets:
      registry:
        required: true
      registry-username:
        required: true
      registry-password:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Set up Go"
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: "Login to Container registry"
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.registry }}
          username: ${{ secrets.registry-username }}
          password: ${{ secrets.registry-password }}      
      - name: Set versions
        run: |
          export INPUT_VERSION="${{ inputs.version }}"
          export C_VERSION="${INPUT_VERSION#v}"

          echo "CONTAINER_IMAGE_VERSION=${C_VERSION}" >> $GITHUB_ENV
          echo "BUNDLE_VERSION=${C_VERSION}" >> $GITHUB_ENV
          echo "CATALOG_VERSION=latest" >> $GITHUB_ENV
      - name: "Build Container image"
        run: |
          make docker/build
          make docker/push
      - name: "Build OLM bundle"
        if: ${{ inputs.olm }}
        run: |
          make bundle/generate
          make bundle/build
          make bundle/push
      - name: "Build OLM Catalog"
        if: ${{ inputs.olm }}
        run: |
          make catalog/build
          make catalog/push
